version: "3"
services:
  cqhttp:
    image: richardchien/cqhttp:latest
    volumes:
      - "./coolq:/home/user/coolq" # 用于保存COOLQ文件的目录
    environment:
      - COOLQ_ACCOUNT=${COOLQ_ACCOUNT} # 指定要登陆的QQ号，用于自动登录
      - FORCE_ENV=true
      - CQHTTP_USE_HTTP=false
      - CQHTTP_USE_WS=false
      - CQHTTP_USE_WS_REVERSE=true
      - CQHTTP_WS_REVERSE_API_URL=ws://nonebot:8080/ws/api/
      - CQHTTP_WS_REVERSE_EVENT_URL=ws://nonebot:8080/ws/event/
    depends_on:
      - nonebot

  nonebot:
    build: .
    expose:
      - "8080"
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - "./coolq:/coolq"
      - ".:/qbot"
    command: poetry run python /qbot/run.py
