version: "3.8"
services:
  cqhttp:
    image: richardchien/cqhttp:latest
    container_name: "iswust_cqhttp"
    volumes:
      - ./data/coolq:/home/user/coolq # 用于保存COOLQ文件的目录
    ports:
      - 9000:9000
    environment:
      - TZ=Asia/Shanghai
      - COOLQ_ACCOUNT=${COOLQ_ACCOUNT} # 指定要登陆的QQ号，用于自动登录
      - VNC_PASSWD=${VNC_PASSWD} # 指定要登陆的QQ号，用于自动登录
      - FORCE_ENV=true
      - CQHTTP_USE_HTTP=false
      - CQHTTP_USE_WS=false
      - CQHTTP_USE_WS_REVERSE=true
      - CQHTTP_WS_REVERSE_API_URL=ws://nonebot:${PORT}/ws/api/
      - CQHTTP_WS_REVERSE_EVENT_URL=ws://nonebot:${PORT}/ws/event/
    depends_on:
      - nonebot

  nonebot:
    build: .
    container_name: "iswust_nonebot"
    expose:
      - ${PORT}
    environment:
      - TZ=Asia/Shanghai
      - QUART_APP=${QUART_APP}
      - QUART_DEBUG=${QUART_DEBUG}
    volumes:
      - .:/qbot
      - ./data/coolq:/coolq
    command: poetry run quart run --host ${HOST} --port ${PORT}
    depends_on:
      - database
      - redis

  redis:
    container_name: "iswust_redis"
    image: "redis:alpine"
    expose:
      - 6379
    ports:
      - 16379:6379
    volumes:
      - redis_data:/data
    entrypoint: redis-server --appendonly yes
    environment:
      - TZ=Asia/Shanghai
    sysctls:
      net.core.somaxconn: "888"

  admin:
    image: dpage/pgadmin4
    container_name: "iswust_pgadmin4"
    ports:
      - 18080:80
    environment:
      - TZ=Asia/Shanghai
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - PGADMIN_CONFIG_CONSOLE_LOG_LEVEL=25
    volumes:
      - admin_data:/var/lib/pgadmin

  database:
    image: postgres
    container_name: "iswust_postgres"
    expose:
      - 5432
    ports:
      - 15432:5432
    environment:
      - TZ=Asia/Shanghai
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - database_data:/var/lib/postgresql/data/

volumes:
  database_data: {}
  admin_data: {}
  redis_data: {}
