version: "3.7"
services:
  cqhttp:
    image: richardchien/cqhttp:latest
    volumes:
      - ${COOLQ_DIR}:/home/user/coolq # 用于保存COOLQ文件的目录
    ports:
      - 9000:9000
    environment:
      - COOLQ_ACCOUNT=${COOLQ_ACCOUNT} # 指定要登陆的QQ号，用于自动登录
      - VNC_PASSWD=${VNC_PASSWD} # 指定要登陆的QQ号，用于自动登录
      - FORCE_ENV=true
      - CQHTTP_USE_HTTP=false
      - CQHTTP_USE_WS=false
      - CQHTTP_USE_WS_REVERSE=true
      - CQHTTP_WS_REVERSE_API_URL=ws://nonebot:${PORT}/ws/api/
      - CQHTTP_WS_REVERSE_EVENT_URL=ws://nonebot:${PORT}/ws/event/
    depends_on:
      - nonebot

  nonebot:
    build: .
    expose:
      - ${PORT}
    environment:
      - TZ=Asia/Shanghai
      - QUART_APP=${QUART_APP}
      - QUART_DEBUG=${QUART_DEBUG}
    volumes:
      - ${COOLQ_DIR}:/coolq
      - .:/qbot
    command: poetry run quart run --host ${HOST} --port ${PORT}
    depends_on:
      - admin

  admin:
    image: dpage/pgadmin4
    ports:
      - 18080:80
    environment:
      - TZ=Asia/Shanghai
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - PGADMIN_CONFIG_CONSOLE_LOG_LEVEL=25
    volumes:
      - admin-data:/var/lib/pgadmin
    depends_on:
      - database

  database:
    image: postgres
    expose:
      - 5432
    environment:
      - TZ=Asia/Shanghai
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - database-data:/var/lib/postgresql/data/

volumes:
  database-data: {}
  admin-data: {}
